name: Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # Atualiza diariamente
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@master
        with:
          github_user_name: GabrielCesar48
          outputs: dist

      - uses: actions/upload-artifact@v2
        with:
          name: snake
          path: dist

      - name: Commit Snake Animation
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
